apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tododb;
    USE tododb;
    CREATE TABLE tasks (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT, start_date DATE, start_time TIME, end_date DATE, end_time TIME, completed TINYINT(1) DEFAULT 0);
